# constants.py

# Court dimensions in meters (approx for tennis)
DOUBLE_LINE_WIDTH = 10.97
SINGLE_LINE_WIDTH = 8.23
HALF_COURT_LINE_HEIGHT = 11.885
NO_MANS_LAND_HEIGHT = 5.49
DOUBLE_ALLY_DIFFERENCE = (DOUBLE_LINE_WIDTH - SINGLE_LINE_WIDTH) / 2

# Player heights (meters)
PLAYER_1_HEIGHT_METERS = 1.80
PLAYER_2_HEIGHT_METERS = 1.75
